#UNO project Ant build configuration file
#Mon Sep 14 19:52:50 CEST 2026
office.install.dir=/opt/libreoffice7.6
sdk.dir=/opt/libreoffice7.6/sdk
uno.java.classpath=vinnie/dist/vinnie.jar, ezvcard/dist/ezvcard.jar, vCardOOo/lib/json-20250107.jar, vCardOOo/lib/UnoHelper.jar
